import { getAccessTokenStorage } from "../../storage"
import { ApiResponse, Task } from "../../type"

export const getTaskList = () : Promise<ApiResponse<Task[]> | null> => {
	return new Promise((resolve) => {
		uni.request<ApiResponse<Task[]>>({
			url: "http://192.168.146.254:3000/tasks/tasks",
			method: "GET",
			header: {
				Authorization: "Bearer " + getAccessTokenStorage()
			},
			timeout: 5000,

			success: (e : RequestSuccess<ApiResponse<Task[]>>) => {
				resolve(e.data)
			},

			fail: (e) => {
				uni.showToast({
					title: e.errMsg,
					icon: "error"
				})

				resolve(null)
			}
		})
	})
}
