import { getAccessTokenStorage } from "../../storage"
import { ApiResponse, UserInfoVO } from "../../type"

export const getUserInfo = () : Promise<ApiResponse<UserInfoVO> | null> => {
	return new Promise((resolve) => {
		uni.request<ApiResponse<UserInfoVO>>({
			url: "http://192.168.146.254:3000/user/getUserInfo",
			method: "GET",
			header: {
				Authorization: "Bearer " + getAccessTokenStorage()
			},
			timeout: 5000,

			success: (e : RequestSuccess<ApiResponse<UserInfoVO>>) => {
				resolve(e.data)
			},

			fail: (e) => {
				uni.showToast({
					title: e.errMsg,
					icon: "error"
				})

				resolve(null)
			}
		})
	})
}
