// 登录请求DTO
export type LoginDTO = {
	account : string;// userName  email  phone
	password : string;
	remember ?: boolean;// 记住我
}

// 用户数据展示
export type UserInfoVO = {
	userName : string;
	nickName : string;
	avatar : string | null;
	email : string;
	phone : string,
	gender : string;
	birthday : number | null;
	signature : string;
	theme : string;
}

// 登录成功后的数据展示
export type LoginUser = {
	accessToken : string;
	refreshToken: string;
}

// 刷新token的dto数据体
export type tokenDto = {
	refreshToken:string;
}
