// token 的状态管理

import { ApiResponse, LoginUser } from "../../type"

// key
const acc = "accessToken-storage"
const ref = "refreshToken-storage"
// 存储accToken
export const setAccessTokenStorage = (data : string) => {
	uni.setStorageSync(acc, data)
}


// 获取accToken
export const getAccessTokenStorage = () : string  => {
	return uni.getStorageSync(acc) as string

}

// 存储refToken
export const setRefreshTokenStorage = (data : string) => {
	uni.setStorageSync(ref, data)
}


// 获取refToken
export const getRefreshTokenStorage = () : string  => {
	return uni.getStorageSync(ref) as string

}

// 删除token
export const removeTokenStorage = () => {
	uni.removeStorageSync(acc)
	uni.removeStorageSync(ref)
}

// 封装刷新token请求
export const refresh = () : Promise<boolean> => {
	console.log('refresh Token')
		return new Promise((resolve) => {
			uni.request<ApiResponse<LoginUser>>({
				url: "http://192.168.146.254:3000/user/refresh",
				method: 'POST',
				data: {
					refreshToken: getRefreshTokenStorage() ? getRefreshTokenStorage() : null
				},
				timeout: 5000,
				success: (e : RequestSuccess<ApiResponse<LoginUser>>) => {
					if (e.data == null) return
					const res = e.data
					// 服务端错误
					if (res.code === 0) {
						uni.showToast({
							title: res.message,
							icon: 'error'
						})
						resolve(false)
						return
					}

					if (res.data == null) return
					// 换新token
					setAccessTokenStorage(res.data?.accessToken as string)
					setRefreshTokenStorage(res.data?.refreshToken as string)
					resolve(true)

				}, fail(e) {
					if (e == null) return
					uni.showToast({
						title: e.data as string,
						icon: 'error'
					})
					resolve(false)
				}
			})
		})
	}
